version: '3.9'

services:
    dev:
        image: ajv-mongoose-converter-dev
        build: 
            context: ../
            dockerfile: docker/dev/Dockerfile
            args:
                - IDIR=ajv-mongoose-converter
                #- BMODE=production # default development on Dockerfile
        volumes:
            - ../:/ws/ajv-mongoose-converter:cached
            # node_modules in un volume temporaneo che non mi sovraccarica il prj reale in debug
            - dev-modules:/ws/ajv-mongoose-converter/node_modules 
            - pnpm-store:/home/node/pnpm/store
        environment:
            # not in .env because .env can be used in prod too
            FORCE_UID: 1001
            FORCE_GID: 1001

    # Overrides default command so things don't shut down after the process ends.
        command: sleep infinity
        deploy:
            resources:
                limits:
                    cpus: 2

volumes:
    dev-modules:
    pnpm-store:

networks:
    default:
        name: docker_default
        external: true
